"""Persistent state for LearnX-Radar.

Two separate concerns, two files (both committed back by the Actions workflow
so state survives across daily runs without external storage):

- seen_skills.json  — dedup: source items already turned into lessons
- skill_memory.json — knowledge state: concepts covered, dates, depth (v2)
- last_scored.json  — this run's ranking, so the dashboard rebuilds from state (v3)
- briefs/           — full lesson brief text, linked from lessons for Perplexity Q&A
"""
from storage import run_history
from storage.state import (
    apply_learned_aliases,
    dutch_due_words,
    dutch_unsubmitted_streak,
    filter_new,
    flatten_aliases,
    load_alias_denylist,
    load_brief,
    load_dutch_memory,
    load_last_scored,
    load_learned_aliases,
    load_memory,
    load_run_history,
    load_seen,
    load_trending_history,
    mark_seen,
    previous_lesson,
    record_dutch_lesson,
    record_dutch_recall,
    record_dutch_review,
    record_lesson,
    record_lesson_rating,
    review_token,
    save_alias_denylist,
    save_brief,
    save_cohort,
    save_dutch_lesson,
    save_dutch_memory,
    save_dutch_progress,
    save_last_scored,
    save_learned_aliases,
    save_memory,
    save_review,
    save_run_history,
    save_seen,
    save_trending_history,
    slugify,
)

__all__ = [
    "load_seen",
    "save_seen",
    "mark_seen",
    "filter_new",
    "load_memory",
    "save_memory",
    "record_lesson",
    "record_lesson_rating",
    "previous_lesson",
    "load_last_scored",
    "save_last_scored",
    "load_trending_history",
    "save_trending_history",
    "save_brief",
    "load_brief",
    "slugify",
    "load_dutch_memory",
    "save_dutch_memory",
    "save_review",
    "review_token",
    "save_dutch_lesson",
    "save_dutch_progress",
    "dutch_due_words",
    "dutch_unsubmitted_streak",
    "record_dutch_lesson",
    "record_dutch_recall",
    "record_dutch_review",
    "load_learned_aliases",
    "save_learned_aliases",
    "apply_learned_aliases",
    "flatten_aliases",
    "load_alias_denylist",
    "save_alias_denylist",
    "load_run_history",
    "save_run_history",
    "save_cohort",
    "run_history",
]
