"""Cross-post the daily lesson to dev.to as a (weekly) draft article — reach + SEO.

dev.to is a community platform, so this runs WEEKLY (config.DEVTO_POST_WEEKDAY) and
creates a DRAFT by default (config.DEVTO_PUBLISHED=False) for review before going
live. One authenticated POST to the Forem API. Degrades gracefully: disabled, no
API key, missing brief, or wrong weekday -> no-op (never breaks the daily run).
"""
from datetime import date

import requests

import config

API = "https://dev.to/api/articles"
_FOOTER = (
    "\n\n---\n\n"
    "*Generated by [LearnX-Radar]({site}) — a free daily developer lesson on what's "
    "rising right now, grounded in real sources. Get it daily on Telegram: "
    "[t.me/learnradar]({channel}).*"
)


def _strip_h1(md: str) -> str:
    """Drop a leading '# Title' so it doesn't duplicate dev.to's own title field."""
    lines = (md or "").splitlines()
    if lines and lines[0].lstrip().startswith("# "):
        lines = lines[1:]
    return "\n".join(lines).lstrip("\n")


def publish(lesson: dict, force: bool = False) -> bool:
    """Create a dev.to article (draft by default) from the lesson brief. Weekly."""
    if not config.DEVTO_PUBLISH_ENABLED:
        return False
    if not force and date.today().weekday() != config.DEVTO_POST_WEEKDAY:
        return False
    key = (config.DEVTO_API_KEY or "").strip()
    body_md = lesson.get("brief_md")
    if not key:
        print("[devto] DEVTO_API_KEY not set — skipping cross-post")
        return False
    if not body_md:
        return False

    title = lesson.get("title") or lesson.get("skill") or "Today's developer lesson"
    body = _strip_h1(body_md) + _FOOTER.format(
        site=config.SITE_URL, channel=config.CHANNEL_URL
    )
    payload = {
        "article": {
            "title": title,
            "body_markdown": body,
            "published": bool(config.DEVTO_PUBLISHED),
            "tags": config.DEVTO_POST_TAGS,
        }
    }
    resp = requests.post(API, json=payload, headers={"api-key": key}, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    state = "published" if config.DEVTO_PUBLISHED else "draft"
    print(f"[devto] created {state}: {data.get('url') or data.get('id')}")
    return True
